import pytest
import csv
import os
from pages.login_page import LoginPage


def load_test_data():
    test_cases = []
    csv_path = os.path.join(os.path.dirname(__file__), '..', 'test_data.csv')
    with open(csv_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            test_cases.append((
                row['username'],
                row['password'],
                row['expected_result'],
                row['test_description']
            ))
    return test_cases


class TestDataDriven:
    """
    Data-Driven Test Suite powered by CSV test data.
    In production this CSV would be AI-generated by Infosys TOPAZ
    analyzing the application and auto-generating test scenarios
    including edge cases and security scenarios automatically.
    """

    @pytest.mark.parametrize("username,password,expected,description",
                             load_test_data())
    def test_login_scenarios(self, driver, base_url,
                             username, password, expected, description):
        print(f"\nTesting: {description}")
        driver.get(f"{base_url}/login")
        login_page = LoginPage(driver)
        login_page.login(username, password)

        if expected == "success":
            assert login_page.is_login_successful(), (
                f"FAILED: {description}"
            )
        else:
            assert login_page.is_login_failed(), (
                f"FAILED: {description}"
            )
